from firebase_admin import auth

from initialise_firebase_admin import app


# uid = '12345'

# custom_token = auth.create_custom_token(uid)

# print(custom_token);


decoded_token = auth.verify_id_token('eyJhbGciOiJSUzI1NiIsImtpZCI6IjNjYmM4ZjIyMDJmNjZkMWIxZTEwMTY1OTFhZTIxNTZiZTM5NWM2ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXlwcm9qZWN0d2l0aGZpcmViYXNlLThhMWU0IiwiYXVkIjoibXlwcm9qZWN0d2l0aGZpcmViYXNlLThhMWU0IiwiYXV0aF90aW1lIjoxNjA4NzE5OTUwLCJ1c2VyX2lkIjoiMTIzNDUiLCJzdWIiOiIxMjM0NSIsImlhdCI6MTYwODcxOTk1MCwiZXhwIjoxNjA4NzIzNTUwLCJlbWFpbCI6InNvbWVvbmUud2l0aC5pZC51cGRhdGVAZW1haWx1cGRhdGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInNvbWVvbmUud2l0aC5pZC51cGRhdGVAZW1haWx1cGRhdGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.irus6TS_jNRTB3p6LtrQejGETDggdih22H62JsBOd4mvwc_EPddWnd7p0n8lQHG5Ia5ryrrOW2i36TIs43cOGCzhRHqDYYp9ETwQJ7nWf7bn1uKOdvJEW5hHlXBOwKZpFaFLzFROVvlUZFNyUlIsXSzmbQG6qSvsjhCWY7bMopUOR7BX7NXFU-cWLQHObRH0m18j2hhjgKMZi-VNRhhC6WNiI6ZGugica5PZJfRCUOhMGvS4xoCGnBWSc6RrRMn3pwaFlmkdCzCwhQirfx-dxn6q1sVmIb6c3rQ3gxLYcDLsNCjv_DKdIRqWbUg7oqRoxr3kIe6jndTkVFPShLeHgw')
print(decoded_token);
# uid = decoded_token['uid']
# print(uid);

# user = auth.get_user_by_email('someone.with.id.update@emailupdate.com')
# print('Successfully fetched user data: {0}'.format(user.uid))